Milestone 3: set up associations
jaflih/SchoolLibrary pull request #3
Opened 2022-04-04 15:01 UTC by jaflih

### Milestone 3: set up associations

- Created Classroom class
- Created the has-many/belongs-to relationship between Classroom and Student
- Created Rental and Book class
- Create the many-to-many relationship between Person and Book using the intermediate class Rental

2022-04-04 18:27 UTC, FrederickMih requested changes
Hi @jaflih , 

You have done a fantastic job so far in this project. Keep up! :rocket: 
There are some issues that you still need to work on to go to the next project but you are almost there!


# To Highlights

-  Git/GitHub workflow has been followed :heavy_check_mark: 
-  Linters are correctly set up :heavy_check_mark: 
-  Pull Request has a title and summary :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-04 18:27 UTC, FrederickMih commented on lib/book.rb
> +  end
- [ ] Great job for implementing this method of adding rentals :+1: . Please let's also make sure that a book should be rented out to a person on a particular date. Hence you will be required to pass in `person` and `date` as a parameter in the `add_rentals` method and to achieve the has_many association, the book itself should be sent as a parameter to create a new rental ie `Rental.new(date, self, person)`. Please let's fix this issue and be sure to receive the comment `Status: Approved` from the next reviewer.

2022-04-04 18:27 UTC, FrederickMih commented on lib/rental.rb
> +  attr_reader :book, :person
- [ ] In the Rental class, a book and a person can also be written. So you will need Getters and Setters methods for the @book and @person instance variables ie `attr_accessor :date, :book, :person`

2022-04-04 18:27 UTC, FrederickMih commented on lib/person.rb
> +  end
- [ ] A book at a particular date is rented out to a person hence you will be required to pass in the `book` and `date` as a parameter to this method and continued as explained above.


  Thanks andnI wish you the best :pray:

2022-04-05 09:44 UTC, jaflih commented on lib/classroom.rb
> +  attr_accessor :label, :students
Hi @FrederickMih, thank you for your feedback.
It's done.

2022-04-05 09:47 UTC, jaflih commented on lib/rental.rb
> +  attr_reader :book, :person
It's done.

2022-04-05 09:52 UTC, jaflih commented on lib/person.rb
> +  end
Ok done

2022-04-05 10:00 UTC, jaflih commented on lib/book.rb
> +  end
ok thank you

2022-04-05 10:12 UTC, t-yanick approved these changes
Hi @jaflih, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-05 10:22 UTC, jaflih commented
@t-yanick 
![thanks](https://user-images.githubusercontent.com/7243132/161733546-f1f7091d-74f1-48ce-b28c-45e4a1d8f4ca.jpeg)

2022-04-05 10:22 UTC, merged